//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkuteSinglePage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int ID { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Tags { get; set; }
    
        public virtual User User { get; set; }
    }
}
