//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkuteSinglePage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concert
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string CityRu { get; set; }
        public string CityBe { get; set; }
        public string CityEn { get; set; }
        public string NameRu { get; set; }
        public string NameBe { get; set; }
        public string NameEn { get; set; }
        public string AddressRu { get; set; }
        public string AddressEn { get; set; }
        public string AddressBe { get; set; }
        public string LogoFilename { get; set; }
        public string PlaceRu { get; set; }
        public string PlaceBe { get; set; }
        public string PlaceEn { get; set; }
        public string ContactsRu { get; set; }
        public string ContactsBe { get; set; }
        public string ConactsEn { get; set; }
    }
}
