//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkuteSinglePage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbum
    {
        public PhotoAlbum()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string TitleRu { get; set; }
        public string TitleEn { get; set; }
        public string TitleBe { get; set; }
    
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
